
services:
  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      # Named volume mounted to the MySQL data directory
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend Server
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      # Docker Compose injects env variables from your local environment
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_AUTH_SECRET: ${JWT_AUTH_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MYSQL_URL: ${MYSQL_URL}

  # Frontend
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mysql_data: